package org.calamares.miga.data.search

import org.calamares.miga.data.ai.OpenRouterDishRecipeGenerationClient
import org.calamares.miga.data.vision.outputLanguageInstruction
import org.calamares.miga.data.vision.RECIPE_JSON_FORMAT
import org.calamares.miga.L10n
import org.calamares.miga.R
import org.calamares.miga.data.vision.RecipeVisionResult
import org.calamares.miga.data.vision.VisionProviderType

/** Genera una receta completa (mismo formato que el reconocimiento por foto, ver
 *  [org.calamares.miga.data.vision.RecipeVisionResultDto]) para un plato ya elegido, a partir de su
 *  nombre y descripción - sin ninguna foto de por medio, el LLM la genera desde su propio
 *  conocimiento. */
interface DishRecipeGenerationClient {
    suspend fun generateRecipe(dish: DishSuggestion, apiKey: String, model: String): RecipeVisionResult
}

fun dishRecipeGenerationClientFor(provider: VisionProviderType): DishRecipeGenerationClient = when (provider) {
    VisionProviderType.GEMINI -> GeminiDishRecipeGenerationClient
    VisionProviderType.ANTHROPIC -> AnthropicDishRecipeGenerationClient
    VisionProviderType.OPENROUTER -> OpenRouterDishRecipeGenerationClient
}

/** Asks for a full recipe for [dish] using the same JSON format as photo transcription. */
internal fun buildDishRecipePrompt(dish: DishSuggestion): String {
    val originText = dish.origin?.takeIf { it.isNotBlank() }?.let { " (a typical dish of $it)" }.orEmpty()
    val contextText = dish.description.takeIf { it.isNotBlank() }?.let { "\nContext: $it" }.orEmpty()
    return """
You are a cooking assistant. Write a complete, realistic and well explained recipe for the dish
"${dish.name}"$originText.$contextText

Return ONLY a JSON object with exactly this format, with no explanations or extra text:
$RECIPE_JSON_FORMAT
Use realistic quantities and ingredients for the number of servings you choose. Put each
preparation step as a separate entry of the "instructions" array, in a logical order. In "source"
state that the recipe was generated by AI (for example "AI-generated"). If you cannot determine a
value, use null (or an empty list) instead of making it up.
""".trimIndent() + outputLanguageInstruction()
}
