package org.calamares.miga.data.search

import org.calamares.miga.L10n
import org.calamares.miga.R
import org.calamares.miga.data.ai.AiCandidate
import org.calamares.miga.data.ai.AiRequest
import org.calamares.miga.data.ai.KnownLabels
import org.calamares.miga.data.ai.knownLabelsInstruction
import org.calamares.miga.data.ai.RECIPE_JSON_FORMAT
import org.calamares.miga.data.ai.complete
import org.calamares.miga.data.ai.outputLanguageInstruction
import org.calamares.miga.data.ai.transcriptionLanguageInstruction
import org.calamares.miga.data.vision.RECIPE_MAX_TOKENS
import org.calamares.miga.data.vision.RecipeVisionResult
import org.calamares.miga.data.vision.parseRecipeAnswer

/** Writes a full recipe for a dish chosen in the AI search, from the model's own knowledge. */
suspend fun AiCandidate.generateRecipe(dish: DishSuggestion, known: KnownLabels = KnownLabels.NONE): RecipeVisionResult {
    val result = complete(AiRequest(buildDishRecipePrompt(dish, known), RECIPE_MAX_TOKENS))
    return parseRecipeAnswer(result) { L10n.str(R.string.couldnt_generate_recipe) }
}

/**
 * Extracts the main recipe from the readable text of a downloaded web page (see RecipeUrlFetcher).
 * The model reads the text; structured data such as schema.org/JSON-LD is not parsed.
 */
suspend fun AiCandidate.importRecipeFromPage(url: String, pageText: String, known: KnownLabels = KnownLabels.NONE): RecipeVisionResult {
    val result = complete(AiRequest(buildUrlImportPrompt(url, pageText, known), RECIPE_MAX_TOKENS))
    return parseRecipeAnswer(result) { L10n.str(R.string.no_recipe_was_found_page) }
}

internal fun buildDishRecipePrompt(dish: DishSuggestion, known: KnownLabels = KnownLabels.NONE): String {
    val originText = dish.origin?.takeIf { it.isNotBlank() }?.let { " (a typical dish of $it)" }.orEmpty()
    val contextText = dish.description.takeIf { it.isNotBlank() }?.let { "\nContext: $it" }.orEmpty()
    return """
You are a cooking assistant. Write a complete, realistic and well explained recipe for the dish
"${dish.name}"$originText.$contextText

Return ONLY a compact JSON object (no indentation or line breaks) with exactly this format, with no explanations or extra text:
$RECIPE_JSON_FORMAT
Use realistic quantities and ingredients for the number of servings you choose. Put each
preparation step as a separate entry of the "instructions" array, in a logical order. In "source"
state that the recipe was generated by AI (for example "AI-generated"). If you cannot determine a
value, use null (or an empty list) instead of making it up.
""".trimIndent() + knownLabelsInstruction(known) + outputLanguageInstruction()
}

internal fun buildUrlImportPrompt(url: String, pageText: String, known: KnownLabels = KnownLabels.NONE): String = """
You are a cooking assistant. Below is the text extracted from a web page ($url) that should contain
a recipe. The text may include noise unrelated to the recipe (navigation menus, ads, comments from
other users, links to other recipes...); ignore it and keep only the main recipe of the page.

Page text:
---
$pageText
---

Return ONLY a compact JSON object (no indentation or line breaks) with exactly this format, with no explanations or extra text:
$RECIPE_JSON_FORMAT
If the text does not contain a recognisable recipe, leave "name" empty. Put the original URL ($url)
in "source". If you cannot determine a value, use null (or an empty list) instead of making it up.
""".trimIndent() + knownLabelsInstruction(known) + transcriptionLanguageInstruction()
